### ISSUE TITLE
Language support: [Python3]

### ISSUE THREAD

**Issue by pylemon** [lppedd/idea-return-highlighter#11]

**Comment by lppedd** [comment]
@pylemon will get it done by next week, as today I'm busy with another plugin.
Being I'm not a Python expert, are there corner/strange cases for the `return` statement that I should be aware of?

I've looked at clojure/lambda expression, but it seems they can only container a single inline expression, so no `return`s.

**Comment by lppedd** [comment]
@pylemon done. See https://github.com/lppedd/idea-return-highlighter/releases/tag/v0.8.0
