### ISSUE TITLE
It doesn't work on version 2020.1

### ISSUE THREAD

**Issue by AprilViolet** [lppedd/idea-return-highlighter#15]
Hello, developer, this plug-in is very good, But It doesn't work on version 2020.1

**Comment by lppedd** [comment]
@AprilViolet hi! Yeah I know... Sorry about that. As you can see I've been pretty busy with other projects.

Ill try to upload a new release tomorrow 😁

**Comment by AprilViolet** [comment]
@lppedd Maybe you said idea-conventional-commit this project, I also installed it. It's also very helpful. Thank you for your efforts

**Comment by lppedd** [comment]
@AprilViolet I'm uploading a new release now. In the meantime, you can edit the `META-INF/plugin.xml `yourself, inside the JAR, with a `until-build` value of `201.*` :smile:

**Comment by lppedd** [comment]
@AprilViolet  https://github.com/lppedd/idea-return-highlighter/releases/tag/0.8.1

**Comment by AprilViolet** [comment]
@lppedd I have received the update, thank you very much.:smile:

**Comment by lppedd** [comment]
@AprilViolet no problem. Feel free to open issues in case. I don't know when I'll handle them, but sooner or later I will :smile:
